### ISSUE TITLE
Exposing Token API

### ISSUE THREAD

**Issue by bukinoshita** [cauequeiroz/spotify-wrapper#1]
It might be better to use a constructor for building wrappers so you don't expose the `token api` and you only set it once.

Eg:
```js
class SpotifyWrapper {
  constructor(token) {
    this.request = request.defaults({
      baseUrl: 'https://api.spotify.com/v1/search',
      timeout: 30000,
      json: true,
      headers: {
        Authorization: `Baerer ${token}`
      }
    })
  }

  handleRequest(config) {
    return new Promise((resolve, reject) => {
      this.request(config)
        .then(data => resolve(data))
        .catch(({ error }) => reject(error.message))
    })
  }

  searchAlbums(query) {
    return this.handleRequest({
      url: '/album',
      method: 'get',
      query: { q: query, type: 'album' }
    })
}
```

So you can use it like

```js
const { searchAlbums } = new SpotifyWrapper(TOKEN_API)

await searchAlbums('blackbear')
// => [...albums]

**Comment by bukinoshita** [comment]
I don't know what you can do with their API, if it's dangerous to expose the token or not... but just to keep in mind to never expose it.

You can take a look here for some examples:

- https://github.com/JMPerez/spotify-web-api-js
- https://github.com/thelinmichael/spotify-web-api-node

**Comment by cauequeiroz** [comment]
I'm working on this wrapper, it's not finish yet, but I see now how dangerous can be to expose something like that haha Thanks for the advice, bro. I'll fix.

**Comment by cauequeiroz** [comment]
Fixed! 👍
